/*
 * SPDX-FileCopyrightText: 2024 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI) <PiaPost@helmholtz-hzi.de>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * This file has to be kept in sync with 'backend-mapping.ts' in psa.app.mobile.
 * If you change this file you must also change it there.
 */

export const backendMapping = [
  { prefix: 'TCSG', url: 'https://train-sb.sormas.ch' },
  { prefix: 'TSSW', url: 'https://test-sb.sormas.ch' },
  { prefix: 'SSTG', url: 'https://test-sb.sormas.ch' },
  { prefix: 'Test', url: 'https://testpia-app.de' },
  { prefix: 'L3pia', url: 'https://pia-app.de' },
  { prefix: 'WaKli', url: 'https://pia-app.de' },
  { prefix: 'RSIST', url: 'https://pia-app.de' },
  { prefix: 'hiubz', url: 'https://pia-app.de' },
  { prefix: 'hiuby', url: 'https://pia-app.de' },
  { prefix: 'mtsur', url: 'https://pia-app.de' },
  { prefix: 'isaks', url: 'https://pia-app.de' },
  { prefix: 'agsvh', url: 'https://pia-app.de' },
  { prefix: 'KOVX', url: 'https://pia-app.de' },
  { prefix: 'XSES', url: 'https://pia-app.de' },
  { prefix: 'KDFC', url: 'https://pia-app.de' },
  { prefix: 'NOBQ', url: 'https://pia-app.de' },
  { prefix: 'NXYK', url: 'https://pia-app.de' },
  { prefix: 'DTVA', url: 'https://pia-app.de' },
  { prefix: 'ZUGS', url: 'https://pia-app.de' },
  { prefix: 'LCOD', url: 'https://pia-app.de' },
  { prefix: 'IQOH', url: 'https://pia-app.de' },
  { prefix: 'XSVV', url: 'https://pia-app.de' },
  { prefix: 'BFBQ', url: 'https://zh-sb.sormas.ch' },
  { prefix: 'MMDE', url: 'https://be-sb.sormas.ch' },
  { prefix: 'KASH', url: 'https://lu-sb.sormas.ch' },
  { prefix: 'GYVQ', url: 'https://ur-sb.sormas.ch' },
  { prefix: 'EJFH', url: 'https://sz-sb.sormas.ch' },
  { prefix: 'PZON', url: 'https://ow-sb.sormas.ch' },
  { prefix: 'DVSI', url: 'https://nw-sb.sormas.ch' },
  { prefix: 'NEVC', url: 'https://gl-sb.sormas.ch' },
  { prefix: 'ZERU', url: 'https://zg-sb.sormas.ch' },
  { prefix: 'VFXA', url: 'https://fr-sb.sormas.ch' },
  { prefix: 'BCSI', url: 'https://so-sb.sormas.ch' },
  { prefix: 'ZVWI', url: 'https://bs-sb.sormas.ch' },
  { prefix: 'QRJT', url: 'https://bl-sb.sormas.ch' },
  { prefix: 'GZHM', url: 'https://sh-sb.sormas.ch' },
  { prefix: 'PJXM', url: 'https://ar-sb.sormas.ch' },
  { prefix: 'UXQN', url: 'https://ai-sb.sormas.ch' },
  { prefix: 'BOSZ', url: 'https://sg-sb.sormas.ch' },
  { prefix: 'EQWL', url: 'https://gr-sb.sormas.ch' },
  { prefix: 'JUYK', url: 'https://ag-sb.sormas.ch' },
  { prefix: 'LLHL', url: 'https://tg-sb.sormas.ch' },
  { prefix: 'VYJW', url: 'https://ti-sb.sormas.ch' },
  { prefix: 'FJTH', url: 'https://vd-sb.sormas.ch' },
  { prefix: 'VBYQ', url: 'https://vs-sb.sormas.ch' },
  { prefix: 'MWAP', url: 'https://ne-sb.sormas.ch' },
  { prefix: 'ANKK', url: 'https://ge-sb.sormas.ch' },
  { prefix: 'DVYS', url: 'https://ju-sb.sormas.ch' },
  { prefix: 'WKOO', url: 'https://fl-sb.sormas.ch' },
  { prefix: 'ZHOY', url: 'https://pia-app.de' },
  { prefix: 'IGSX', url: 'https://pia-app.de' },
  { prefix: 'RFEE', url: 'https://pia-app.de' },
  { prefix: 'ezdve', url: 'https://pia-app.de' },
  { prefix: 'kawkh', url: 'https://pia-app.de' },
  { prefix: 'wievb', url: 'https://pia-app.de' },
  { prefix: 'uzglc', url: 'https://pia-app.de' },
  { prefix: 'PBUG', url: 'https://pia-app.de' },
  { prefix: 'VRZL', url: 'https://pia-app.de' },
  { prefix: 'YSER', url: 'https://pia-app.de' },
  { prefix: 'SQUY', url: 'https://pia-app.de' },
  { prefix: 'OCHO', url: 'https://testpia-app.de' },
  { prefix: 'CSCQ', url: 'https://testpia-app.de' },
  { prefix: 'THNA', url: 'https://testpia-app.de' },
  { prefix: 'BTOB', url: 'https://testpia-app.de' },
  { prefix: 'LOCAL', url: 'https://pia-app' },
  { prefix: 'mdmy', url: 'https://pia-release.de' },
  { prefix: 'iwpx', url: 'https://pia-release.de' },
  { prefix: 'hsbo', url: 'https://pia-release.de' },
  { prefix: 'waog', url: 'https://pia-release.de' },
  { prefix: 'zcxj', url: 'https://pia-release.de' },
  { prefix: 'zozk', url: 'https://pia-release.de' },
  { prefix: 'xhvs', url: 'https://pia-release.de' },
  { prefix: 'agde', url: 'https://pia-release.de' },
  { prefix: 'xfuj', url: 'https://pia-release.de' },
  { prefix: 'jxth', url: 'https://pia-release.de' },
  { prefix: 'pjno', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'mhjf', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'cqiq', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'rbvu', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'pgtx', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'rxvn', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'veuh', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'cwhf', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'pgif', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'xsgh', url: 'https://pia-epi.med.uni-muenchen.de' },
  { prefix: 'hkrn', url: 'https://pia-app.de' },
  { prefix: 'ijpx', url: 'https://pia-app.de' },
  { prefix: 'kewu', url: 'https://pia-app.de' },
  { prefix: 'mvob', url: 'https://pia-app.de' },
  { prefix: 'rwep', url: 'https://pia-app.de' },
  { prefix: 'diaf', url: 'https://pia-app.de' },
  { prefix: 'ombr', url: 'https://pia-app.de' },
  { prefix: 'gqex', url: 'https://pia-app.de' },
  { prefix: 'bpxb', url: 'https://pia-app.de' },
  { prefix: 'oodn', url: 'https://pia-app.de' },
];
