# Generated by psa.util.repo-tool, do not edit by hand!

group "default" {
  targets = [ 
"k8s", "psa_app_mobile", "psa_app_web", "psa_lib_auth-server-client", "psa_lib_charts", "psa_lib_hapi-i18n-plugin", "psa_lib_http-clients-internal", "psa_lib_licensecollector", "psa_lib_messagequeue", "psa_lib_publicapi", "psa_lib_service-core", "psa_lib_templatepipeline", "psa_server_apigateway", "psa_server_autheventproxy", "psa_server_eventhistory", "psa_server_jobscheduler", "psa_server_publicapi", "psa_service_analyzerservice", "psa_service_complianceservice", "psa_service_feedbackstatisticservice", "psa_service_loggingservice", "psa_service_notificationservice", "psa_service_personaldataservice", "psa_service_questionnaireservice", "psa_service_sampletrackingservice", "psa_service_sormasservice", "psa_service_userservice", "psa_test_data", "psa_utils_repo-tool"
  ]
}

variable "TAG" {
  default = "develop"
}

variable "IMAGE_REGISTRY" {
  default = "pia"
}

target "k8s" {
  context = "."
  dockerfile = "k8s/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/k8s-npm-install:${TAG}" ]
  args = {
    DIR = "k8s"
  }
}
target "psa_app_mobile" {
  context = "."
  dockerfile = "psa.app.mobile/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.app.mobile-npm-install:${TAG}" ]
  args = {
    DIR = "psa.app.mobile"
  }
}
target "psa_app_web" {
  context = "."
  dockerfile = "psa.app.web/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.app.web-npm-install:${TAG}" ]
  args = {
    DIR = "psa.app.web"
  }
}
target "psa_lib_auth-server-client" {
  context = "."
  dockerfile = "psa.lib.auth-server-client/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.auth-server-client-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.auth-server-client"
  }
}
target "psa_lib_charts" {
  context = "."
  dockerfile = "psa.lib.charts/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.charts-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.charts"
  }
}
target "psa_lib_hapi-i18n-plugin" {
  context = "."
  dockerfile = "psa.lib.hapi-i18n-plugin/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.hapi-i18n-plugin-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.hapi-i18n-plugin"
  }
}
target "psa_lib_http-clients-internal" {
  context = "."
  dockerfile = "psa.lib.http-clients-internal/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.http-clients-internal-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.http-clients-internal"
  }
}
target "psa_lib_licensecollector" {
  context = "."
  dockerfile = "psa.lib.licensecollector/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.licensecollector-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.licensecollector"
  }
}
target "psa_lib_messagequeue" {
  context = "."
  dockerfile = "psa.lib.messagequeue/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.messagequeue-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.messagequeue"
  }
}
target "psa_lib_publicapi" {
  context = "."
  dockerfile = "psa.lib.publicapi/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.publicapi-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.publicapi"
  }
}
target "psa_lib_service-core" {
  context = "."
  dockerfile = "psa.lib.service-core/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.service-core-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.service-core"
  }
}
target "psa_lib_templatepipeline" {
  context = "."
  dockerfile = "psa.lib.templatepipeline/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.lib.templatepipeline-npm-install:${TAG}" ]
  args = {
    DIR = "psa.lib.templatepipeline"
  }
}
target "psa_server_apigateway" {
  context = "."
  dockerfile = "psa.server.apigateway/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.server.apigateway-npm-install:${TAG}" ]
  args = {
    DIR = "psa.server.apigateway"
  }
}
target "psa_server_autheventproxy" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.server.autheventproxy-npm-install:${TAG}" ]
  args = {
    DIR = "psa.server.autheventproxy"
  }
}
target "psa_server_eventhistory" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.server.eventhistory-npm-install:${TAG}" ]
  args = {
    DIR = "psa.server.eventhistory"
  }
}
target "psa_server_jobscheduler" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.server.jobscheduler-npm-install:${TAG}" ]
  args = {
    DIR = "psa.server.jobscheduler"
  }
}
target "psa_server_publicapi" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.server.publicapi-npm-install:${TAG}" ]
  args = {
    DIR = "psa.server.publicapi"
  }
}
target "psa_service_analyzerservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.analyzerservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.analyzerservice"
  }
}
target "psa_service_complianceservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.complianceservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.complianceservice"
  }
}
target "psa_service_feedbackstatisticservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.feedbackstatisticservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.feedbackstatisticservice"
  }
}
target "psa_service_loggingservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.loggingservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.loggingservice"
  }
}
target "psa_service_notificationservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.notificationservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.notificationservice"
  }
}
target "psa_service_personaldataservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.personaldataservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.personaldataservice"
  }
}
target "psa_service_questionnaireservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.questionnaireservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.questionnaireservice"
  }
}
target "psa_service_sampletrackingservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.sampletrackingservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.sampletrackingservice"
  }
}
target "psa_service_sormasservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.sormasservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.sormasservice"
  }
}
target "psa_service_userservice" {
  context = "."
  dockerfile = "docker-templates/nodejs/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.service.userservice-npm-install:${TAG}" ]
  args = {
    DIR = "psa.service.userservice"
  }
}
target "psa_test_data" {
  context = "."
  dockerfile = "psa.test.data/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.test.data-npm-install:${TAG}" ]
  args = {
    DIR = "psa.test.data"
  }
}
target "psa_utils_repo-tool" {
  context = "."
  dockerfile = "psa.utils.repo-tool/Dockerfile"
  target = "npm-install"
  tags = [ "${IMAGE_REGISTRY}/psa.utils.repo-tool-npm-install:${TAG}" ]
  args = {
    DIR = "psa.utils.repo-tool"
  }
}