apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Job
      name: pia-precheck
    patch: |-
      $patch: delete
      kind: Job
      metadata:
        name: 'ANY' # name doesn't matter but must be specified

  - target:
      kind: ServiceAccount
      name: pia-precheck
    patch: |-
      $patch: delete
      kind: ServiceAccount
      metadata:
        name: 'ANY' # name doesn't matter but must be specified
