/*
 * SPDX-FileCopyrightText: 2021 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI) <PiaPost@helmholtz-hzi.de>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * This file has to be kept in sync with 'backend-mapping.js' in psa.service.userservice.
 * If you change this file you must also change it there.
 */

export const backendMapping = [
  { prefix: 'TCSG', url: 'https://train-sb.sormas.ch' },
  { prefix: 'SPTS', url: 'https://pentest-sb-pia.sormas-oegd.de' },
  { prefix: 'DSTG', url: 'https://sb-pia-ch.sormas.netzlink.com' },
  { prefix: 'RSTG', url: 'https://release-pia-ch.sormas.netzlink.com' },
  { prefix: 'TSSW', url: 'https://test-sb.sormas.ch' },
  { prefix: 'SSTG', url: 'https://test-sb.sormas.ch' },
  { prefix: 'Test', url: 'https://testpia-app.de' },
  { prefix: 'L3pia', url: 'https://pia-app.de' },
  { prefix: 'WaKli', url: 'https://pia-app.de' },
  { prefix: 'RSIST', url: 'https://pia-app.de' },
  { prefix: 'hiubz', url: 'https://pia-app.de' },
  { prefix: 'hiuby', url: 'https://pia-app.de' },
  { prefix: 'mtsur', url: 'https://pia-app.de' },
  { prefix: 'isaks', url: 'https://pia-app.de' },
  { prefix: 'agsvh', url: 'https://pia-app.de' },
  { prefix: 'Dtest', url: 'https://pia-develop.netzlink.com' },
  { prefix: 'Rtest', url: 'https://pia-release.netzlink.com' },
  { prefix: 'BFBQ', url: 'https://zh-sb.sormas.ch' },
  { prefix: 'MMDE', url: 'https://be-sb.sormas.ch' },
  { prefix: 'KASH', url: 'https://lu-sb.sormas.ch' },
  { prefix: 'GYVQ', url: 'https://ur-sb.sormas.ch' },
  { prefix: 'EJFH', url: 'https://sz-sb.sormas.ch' },
  { prefix: 'PZON', url: 'https://ow-sb.sormas.ch' },
  { prefix: 'DVSI', url: 'https://nw-sb.sormas.ch' },
  { prefix: 'NEVC', url: 'https://gl-sb.sormas.ch' },
  { prefix: 'ZERU', url: 'https://zg-sb.sormas.ch' },
  { prefix: 'VFXA', url: 'https://fr-sb.sormas.ch' },
  { prefix: 'BCSI', url: 'https://so-sb.sormas.ch' },
  { prefix: 'ZVWI', url: 'https://bs-sb.sormas.ch' },
  { prefix: 'QRJT', url: 'https://bl-sb.sormas.ch' },
  { prefix: 'GZHM', url: 'https://sh-sb.sormas.ch' },
  { prefix: 'PJXM', url: 'https://ar-sb.sormas.ch' },
  { prefix: 'UXQN', url: 'https://ai-sb.sormas.ch' },
  { prefix: 'BOSZ', url: 'https://sg-sb.sormas.ch' },
  { prefix: 'EQWL', url: 'https://gr-sb.sormas.ch' },
  { prefix: 'JUYK', url: 'https://ag-sb.sormas.ch' },
  { prefix: 'LLHL', url: 'https://tg-sb.sormas.ch' },
  { prefix: 'VYJW', url: 'https://ti-sb.sormas.ch' },
  { prefix: 'FJTH', url: 'https://vd-sb.sormas.ch' },
  { prefix: 'VBYQ', url: 'https://vs-sb.sormas.ch' },
  { prefix: 'MWAP', url: 'https://ne-sb.sormas.ch' },
  { prefix: 'ANKK', url: 'https://ge-sb.sormas.ch' },
  { prefix: 'DVYS', url: 'https://ju-sb.sormas.ch' },
  { prefix: 'WKOO', url: 'https://fl-sb.sormas.ch' },
  { prefix: 'VJHE', url: 'https://release-pia-de.sormas.netzlink.com' },
  { prefix: 'XLYK', url: 'https://sb-pia.sormas.netzlink.com' },
  { prefix: 'LITZ', url: 'https://demo-sb-pia.sormas.netzlink.com' },
  { prefix: 'ADRT', url: 'https://schulung-sb-de.sormas.netzlink.com' },
  { prefix: 'ZHOY', url: 'https://pia-app.de' },
  { prefix: 'IGSX', url: 'https://pia-app.de' },
  { prefix: 'RFEE', url: 'https://pia-app.de' },
  { prefix: 'ezdve', url: 'https://pia-app.de' },
  { prefix: 'kawkh', url: 'https://pia-app.de' },
  { prefix: 'wievb', url: 'https://pia-app.de' },
  { prefix: 'uzglc', url: 'https://pia-app.de' },
  { prefix: 'PBUG', url: 'https://pia-app.de' },
  { prefix: 'VRZL', url: 'https://pia-app.de' },
  { prefix: 'YSER', url: 'https://pia-app.de' },
  { prefix: 'SQUY', url: 'https://pia-app.de' },
  { prefix: 'OCHO', url: 'https://testpia-app.de' },
  { prefix: 'CSCQ', url: 'https://testpia-app.de' },
  { prefix: 'THNA', url: 'https://testpia-app.de' },
  { prefix: 'BTOB', url: 'https://testpia-app.de' },
  { prefix: 'MKPY', url: 'https://ammerland-sb.sormas-oegd.de' },
  { prefix: 'VWUE', url: 'https://landkreis-aurich-sb.sormas-oegd.de' },
  { prefix: 'LTRO', url: 'https://braunschweig-sb.sormas-oegd.de' },
  { prefix: 'TPVC', url: 'https://landkreis-celle-sb.sormas-oegd.de' },
  { prefix: 'JYZS', url: 'https://cloppenburg-sb.sormas-oegd.de' },
  { prefix: 'BRWP', url: 'https://landkreis-cuxhaven-sb.sormas-oegd.de' },
  { prefix: 'LRWZ', url: 'https://delmenhorst-sb.sormas-oegd.de' },
  { prefix: 'ELQV', url: 'https://diepholz-sb.sormas-oegd.de' },
  { prefix: 'JKMY', url: 'https://emsland-sb.sormas-oegd.de' },
  { prefix: 'BAYL', url: 'https://friesland-sb.sormas-oegd.de' },
  { prefix: 'HZHU', url: 'https://gifhorn-sb.sormas-oegd.de' },
  { prefix: 'LSCR', url: 'https://goslar-sb.sormas-oegd.de' },
  { prefix: 'CXUY', url: 'https://goettingen-sb.sormas-oegd.de' },
  { prefix: 'PLWO', url: 'https://grafschaft-bentheim-sb.sormas-oegd.de' },
  { prefix: 'MFHF', url: 'https://hameln-pyrmont-sb.sormas-oegd.de' },
  { prefix: 'NODI', url: 'https://hannover-sb.sormas-oegd.de' },
  { prefix: 'WQJI', url: 'https://landkreis-harburg-sb.sormas-oegd.de' },
  { prefix: 'NTXG', url: 'https://landkreis-heidekreis-sb.sormas-oegd.de' },
  { prefix: 'CRBK', url: 'https://helmstedt-sb.sormas-oegd.de' },
  { prefix: 'ZMOI', url: 'https://landkreishildesheim-sb.sormas-oegd.de' },
  { prefix: 'OSZV', url: 'https://holzminden-sb.sormas-oegd.de' },
  { prefix: 'ZJEG', url: 'https://landkreis-leer-sb.sormas-oegd.de' },
  { prefix: 'COUP', url: 'https://landkreis-lueneburg-sb.sormas-oegd.de' },
  { prefix: 'XBXX', url: 'https://lk-nienburg-sb.sormas-oegd.de' },
  { prefix: 'VLQM', url: 'https://landkreis-northeim-sb.sormas-oegd.de' },
  { prefix: 'NLKA', url: 'https://oldenburg-sb.sormas-oegd.de' },
  { prefix: 'NZXW', url: 'https://landkreis-oldenburg-sb.sormas-oegd.de' },
  { prefix: 'DJKR', url: 'https://landkreis-osnabrück-sb.sormas-oegd.de' },
  { prefix: 'YPCM', url: 'https://landkreis-osterholz-sb.sormas-oegd.de' },
  { prefix: 'IBUA', url: 'https://gesundheitsamt-peine-sb.sormas-oegd.de' },
  { prefix: 'CEIC', url: 'https://landkreis-rotenburg-sb.sormas-oegd.de' },
  { prefix: 'YEBM', url: 'https://salzgitter-sb.sormas-oegd.de' },
  { prefix: 'KIVH', url: 'https://schaumburg-sb.sormas-oegd.de' },
  { prefix: 'GKHT', url: 'https://landkreis-stade-sb.sormas-oegd.de' },
  { prefix: 'BFLQ', url: 'https://landkreis-uelzen-sb.sormas-oegd.de' },
  { prefix: 'OFZB', url: 'https://luechow-dannenberg-sb.sormas-oegd.de' },
  { prefix: 'OMYZ', url: 'https://landkreis-vechta-sb.sormas-oegd.de' },
  { prefix: 'MGRM', url: 'https://landkreis-verden-sb.sormas-oegd.de' },
  { prefix: 'BSMK', url: 'https://landkreis-wesermarsch-sb.sormas-oegd.de' },
  { prefix: 'TKMN', url: 'https://wilhelmshaven-sb.sormas-oegd.de' },
  { prefix: 'WLIR', url: 'https://landkreis-wittmund-sb.sormas-oegd.de' },
  { prefix: 'CATG', url: 'https://lkwf-sb.sormas-oegd.de' },
  { prefix: 'FULP', url: 'https://wolfsburg-sb.sormas-oegd.de' },
  { prefix: 'BFAP', url: 'https://bremerhaven-sb.sormas-oegd.de' },
  { prefix: 'UGJJ', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'XOUW', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'XMQE', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'VVWH', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'HJHV', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'USYC', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'ZMSW', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'DOFN', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'DFCO', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'CNQG', url: 'https://qpia.imise.uni-leipzig.de' },
  { prefix: 'VQBU', url: 'https://pia.ship-med.uni-greifswald.de' },
  { prefix: 'RCHN', url: 'https://pia.ship-med.uni-greifswald.de' },
  { prefix: 'RYEY', url: 'https://pia.ship-med.uni-greifswald.de' },
  { prefix: 'ITPH', url: 'https://pia.ship-med.uni-greifswald.de' },
  { prefix: 'JTHB', url: 'https://pia.ship-med.uni-greifswald.de' },
];
