apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # remove servicemonitor objects
  - target:
      kind: ServiceMonitor
    patch: |-
      $patch: delete
      kind: ServiceMonitor
      metadata:
        name: 'ANY' # name doesn't matter but must be specified
