#
# SPDX-FileCopyrightText: 2024 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI) <PiaPost@helmholtz-hzi.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#

parent=keycloak.v3
deprecatedMode=false
favIcon=/favicon.png
logo=pia_logo.png
logoUrl=https://info-pia.de/
locales=de-DE,de-CH,en-US,fr-FR,es-ES
title=PIA Account Management
