ALTER TABLE probands DISABLE TRIGGER ALL;
ALTER TABLE questionnaires DISABLE TRIGGER ALL;
ALTER TABLE answers DISABLE TRIGGER ALL;
ALTER TABLE questionnaire_instances DISABLE TRIGGER ALL;
ALTER TABLE lab_results DISABLE TRIGGER ALL;
