ALTER TABLE users ENABLE TRIGGER ALL;
ALTER TABLE questionnaires ENABLE TRIGGER ALL;
ALTER TABLE answers ENABLE TRIGGER ALL;
ALTER TABLE questionnaire_instances ENABLE TRIGGER ALL;
ALTER TABLE study_users ENABLE TRIGGER ALL;
ALTER TABLE lab_results ENABLE TRIGGER ALL;
