ALTER TABLE probands ENABLE TRIGGER ALL;
ALTER TABLE questionnaires ENABLE TRIGGER ALL;
ALTER TABLE answers ENABLE TRIGGER ALL;
ALTER TABLE questionnaire_instances ENABLE TRIGGER ALL;
ALTER TABLE lab_results ENABLE TRIGGER ALL;
