apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
metadata:
  name: local-k3d

namespace: pia

resources:
  - ../../base
  - internal-secrets.yaml

components:
  - ../../components/local-development
  - ../../components/custom-registry
  # - ../../components/theming-example  # Uncomment to enable theming example

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/replicas"
        value: 1
