# The following resources will be created manually within a skaffold before deploy hook.
# This way we can keep the data in the volumes after skaffold was stopped.

apiVersion: v1
kind: Namespace
metadata:
  name: pia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pia
  name: qpiaservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pia
  name: ewpiaservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pia
  name: ipiaservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pia
  name: messagequeue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
