include:
  - local: ci/rules.yml
  - local: ci/k8s.yml

openapi-generate:
  extends:
    - .job-exclude-schedules-pipelines
    - .no-cpu-request
  stage: prepare
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$FOLDER-npm-install:$IMAGE_ID
  script:
    - ln -s $NODE_PATH $FOLDER/node_modules
    - cd $FOLDER
    - npm run build.openapi
  artifacts:
    paths:
      - $FOLDER/spec/openapi.yaml
    expire_in: 1 week
  needs:
    - job: npm-install
      artifacts: false
  parallel:
    matrix:
      - FOLDER: !reference [.modules, array, openapi]
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH =~ /^develop/
    - if: $CI_COMMIT_BRANCH =~ /^release/

openapi-check:
  extends:
    - .job-exclude-schedules-pipelines
    - .no-cpu-request
  stage: test
  image: node:20.3.0-buster-slim@sha256:a0f92f6970cb1fd5e9b6039a8f428616a9b9ed3633360c6b84dcc6aa5c7d5723
  variables:
    GIT_DEPTH: '1'
    CACHE_DIR: '$CI_PROJECT_DIR/node_modules'
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - $CACHE_DIR
  before_script:
    - npm config set cache $CACHE_DIR --global
  script:
    - npm install -g openapi-merge-cli
    - OUTPUT=./docs/openapi.reference.yaml ./psa.utils.scripts/openapi/generate-merge-config.sh
    - openapi-merge-cli
    - diff ./docs/openapi.yaml ./docs/openapi.reference.yaml
  needs:
    - job: openapi-generate
      artifacts: true
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH =~ /^develop/
    - if: $CI_COMMIT_BRANCH =~ /^release/

openapi-validate:
  extends:
    - .job-exclude-schedules-pipelines
    - .no-cpu-request
  stage: test
  image: node:20.3.0-buster-slim@sha256:a0f92f6970cb1fd5e9b6039a8f428616a9b9ed3633360c6b84dcc6aa5c7d5723
  variables:
    GIT_DEPTH: '1'
    CACHE_DIR: '$CI_PROJECT_DIR/node_modules'
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - $CACHE_DIR
  before_script:
    - npm config set cache $CACHE_DIR --global
  script:
    - npm install -g @seriousme/openapi-schema-validator
    - validate-api ./docs/openapi.yaml
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH =~ /^develop/
    - if: $CI_COMMIT_BRANCH =~ /^release/
